In [28]:
# import dependencies
import psycopg2

import pandas as pd
import csv, os
import warnings
warnings.filterwarnings("ignore")

# SQL Alchemy
from sqlalchemy import create_engine

from config import username, password

In [29]:
#Read CSV files into dataFrames
USA_WVS_2017_Data = pd.read_csv('Resources/USA_WVS_2017.csv')
Russia_WVS_2017_Data = pd.read_csv('Resources/Russia_WVS_2017.csv')
WHS_2017_Data = pd.read_csv("Resources/WHS_2017.csv")

# Convert CSV to Data Frame
USA_WVS_2017_Data = pd.DataFrame(USA_WVS_2017_Data)
Russia_WVS_2017_Data = pd.DataFrame(Russia_WVS_2017_Data)
WHS_2017_Data = pd.DataFrame(WHS_2017_Data)

# preview Data Frame
USA_WVS_2017_Data.head()
#Russia_WVS_2017_Data.head()
#WHS_2017_Data.head()

,version: Version of Data File,doi: Digital Object Identifier,B_COUNTRY: ISO 3166-1 numeric country code,B_COUNTRY_ALPHA: ISO 3166-1 alpha-3 country code,C_COW_NUM: CoW country code numeric,C_COW_ALPHA: CoW country code alpha,A_YEAR: Year of survey,D_INTERVIEW: Interview ID,J_INTDATE: Date of interview,FW_END: Year/month of end-fieldwork,...,WEIGHT4A: Overall Secular Values-4: Weight 4a,WEIGHT4B: Emancipative Values-4: Weight 4b,RESEMAVALBWGT: Weight for Emancipative values,RESEMAVALWGT: Weight for Emancipative values,SECVALBWGT: Weight for overall secular values Short Version,Y001_1: Materialist/postmaterialist 12-item index: Component 1,Y001_2: Materialist/postmaterialist 12-item index: Component 2,Y001_3: Materialist/postmaterialist 12-item index: Component 3,Y001_4: Materialist/postmaterialist 12-item index: Component 4,Y001_5: Materialist/postmaterialist 12-item index: Component 5
0,0.0,0.0,United States,USA,United States of America,USA,2017,USA,2017 May,Jan 2017 to Dec 2021,...,Complete,Complete,0-1,0-1,0-1,0,0,0,0,0
1,0.0,0.0,United States,USA,United States of America,USA,2017,USA,2017 May,Jan 2017 to Dec 2021,...,Complete,Complete,0-1,0-1,0-1,1,1,1,1,1
2,0.0,0.0,United States,USA,United States of America,USA,2017,USA,2017 May,Jan 2017 to Dec 2021,...,Complete,Complete,0-1,0-1,0-1,1,0,1,0,1
3,0.0,0.0,United States,USA,United States of America,USA,2017,USA,2017 May,Jan 2017 to Dec 2021,...,Complete,Complete,0-1,0-1,0-1,0,0,1,0,0
4,0.0,0.0,United States,USA,United States of America,USA,2017,USA,2017 May,Jan 2017 to Dec 2021,...,Complete,Complete,0-1,0-1,0-1,0,1,1,0,0

In [30]:
USA_WVS_2017_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2596 entries, 0 to 2595
Columns: 394 entries, version: Version of Data File to Y001_5: Materialist/postmaterialist 12-item index: Component 5
dtypes: float64(2), int64(7), object(385)
memory usage: 7.8+ MB

In [31]:
# Clean up of USA_WVS_2017 data file
# since there are 394 columns, we will make another dataframe with just with the columns that we wanted
USA_WVS_2017_Data = USA_WVS_2017_Data.drop(columns=['version: Version of Data File','doi: Digital Object Identifier',
          'B_COUNTRY_ALPHA: ISO 3166-1 alpha-3 country code','C_COW_NUM: CoW country code numeric',
          'C_COW_ALPHA: CoW country code alpha','D_INTERVIEW: Interview ID'])

In [32]:
#New data frame with few columns... (We need to add other necessary columns related to happiness)
USA_WVS_2017_new = USA_WVS_2017_Data[['B_COUNTRY: ISO 3166-1 numeric country code', 'A_YEAR: Year of survey',
                                     'N_REGION_ISO: Region ISO 3166-2','H_URBRURAL: Urban-Rural']]

In [33]:
USA_WVS_2017_new.head()

,B_COUNTRY: ISO 3166-1 numeric country code,A_YEAR: Year of survey,N_REGION_ISO: Region ISO 3166-2,H_URBRURAL: Urban-Rural
0,United States,2017,US-OK Oklahoma,Urban
1,United States,2017,US-TX Texas,Urban
2,United States,2017,US-FL Florida,Urban
3,United States,2017,US-FL Florida,Urban
4,United States,2017,US-FL Florida,Urban

In [35]:
# Create Engine for project2 data

engine = create_engine(f"postgresql://{username}:{password}@localhost/project2")

conn = engine.connect()

In [ ]:
#uploading to respecive tables in project2 database

USA_WVS_2017_new.to_sql('USA_WVS_2017', con=conn, if_exists='replace',
          index=False)

Russia_WVS_2017_new.to_sql('Russia_WVS_2017', con=conn, if_exists='replace',
          index=False)

WHS_2017_new.to_sql('WHS_2017', con=conn, if_exists='replace',
          index=False)